Add the Contact page (CU-hjwg2y)
bravetechnologycoop/brave-alert-app pull request #6
Opened 2021-03-04 23:43 UTC by trisapeace

- Submit the form through Google Forms (let me know if you have issues setting this up)
- Gets location name from the Redux store

TODO: 
* Add new envrionment variables to `bitrise.yml` once #3 has been merged
* Specify the Roboto font after #4 has been merged
* Add ContactBraveBoxes after #4 has been merged

2021-03-04 23:43 UTC, trisapeace commented
Task linked: [CU-hjwg2y Frontend: Contact Form: Implementation (submit will send an e mail)](https://app.clickup.com/t/hjwg2y)

2021-03-05 01:07 UTC, trisapeace commented on src/components/HistoricAlert/HistoricAlert.stories.jsx
> +storiesOf('HistoricAlert', module)
I decided that our story category name should exactly match the component's name. So that's why this changed.

2021-03-05 01:07 UTC, trisapeace commented on src/redux/slices/locationSlice.js
> +  // I anticipate things like whether this is a Buttons and/or Sensors location would also go in here
Although I can also see the location name being out of sync between Buttons and Sensors, which would be a pain. In which case, this `locationSlice` might make more sense split up into `buttonLocationSlice` and `sensorLocationSlice`. But that can come in the future if need be.

2021-03-05 01:07 UTC, trisapeace commented on src/screens/ContactScreen.jsx
> +  // Using component state for these values because this state doesn't need to be shared and isn't important to retain
What do you think about having component-level state for values like these?
I could see an argument for having everything in the redux store, but the Internet seems to be divided about either philosophy around this.

2021-03-05 01:07 UTC, trisapeace commented on src/services/FetchService.js
> +const HTTP = {}
Changed this so that I could use these constants when making my custom response handler in `ContactScreen.jsx`. I only needed to use `HTTP.OK_200`, but I could see the rest of them being useful in other instances and it felt weird to only export the one.

2021-03-05 01:09 UTC, trisapeace commented on .env.example
>  # Base URLs for the two backend systems (do not include the protocol)
Reminder to self that I still need to do:
* Add new envrionment variables to bitrise.yml once #3 has been merged
* Specify the Roboto font after #4 has been merged
* Add ContactBraveBoxes after #4 has been merged
* Fix the failing npm audit by rebasing after #5 has been merged

2021-03-06 01:21 UTC, trisapeace commented on src/components/FormTextInput/FormTextInput.stories.jsx
> +  .add('One line', () => <FormTextInput>Name (This will throw an error if you type in the box in storybook):</FormTextInput>)
Got this thanks to Richard pointing out his `CreateAccountForm.stories.jsx` file.

2021-03-23 06:13 UTC, schwarrrtz commented on .env.example
> +# You will need to change the end of the URI to /formResponse instead of /viewform
I'm currently having issues running the app to test this, but I was able to populate the `.env` by following these instructions. One small thing, the file hierarchy described here is missing the top-level Alert App directory.

2021-03-23 16:33 UTC, trisapeace commented on .env.example
> +# You will need to change the end of the URI to /formResponse instead of /viewform
Fixed.

2021-03-23 21:52 UTC, schwarrrtz requested changes
This looks great, I ran it in iOS simulator and the contact form submission works for me. Other than possibly renaming the HTTP object to HTTP_STATUS to make it more clear, I think this is good to go, although I haven't tested it on Android.

2021-03-23 21:52 UTC, schwarrrtz commented on src/services/FetchService.js
> +const HTTP = {}
This makes sense, but would it be OK to rename the object to something like `HTTP_STATUS`? I foresee myself getting confused about whether this is a http library.

2021-03-23 21:52 UTC, schwarrrtz commented on src/screens/ContactScreen.jsx
> +  // Using component state for these values because this state doesn't need to be shared and isn't important to retain
I'm not 100% up to speed with Redux yet, but I think keeping things local is a good approach unless there's a reason for it to be shared more broadly.

2021-03-23 22:25 UTC, trisapeace commented on .env.example
>  # Base URLs for the two backend systems (do not include the protocol)
Done.

2021-03-23 23:35 UTC, trisapeace commented on src/services/FetchService.js
> +const HTTP = {}
Makes sense to me. Done.

2021-03-24 02:52 UTC, merged